// Code generated by MockGen. DO NOT EDIT.
// Source: ./usecase/port/auth.go

// Package mock_port is a generated GoMock package.
package mock_port

import (
	reflect "reflect"

	handler "github.com/faciam_dev/twitter_block2mute/backend/adapter/gateway/handler"
	entity "github.com/faciam_dev/twitter_block2mute/backend/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockAuthInputPort is a mock of AuthInputPort interface.
type MockAuthInputPort struct {
	ctrl     *gomock.Controller
	recorder *MockAuthInputPortMockRecorder
}

// MockAuthInputPortMockRecorder is the mock recorder for MockAuthInputPort.
type MockAuthInputPortMockRecorder struct {
	mock *MockAuthInputPort
}

// NewMockAuthInputPort creates a new mock instance.
func NewMockAuthInputPort(ctrl *gomock.Controller) *MockAuthInputPort {
	mock := &MockAuthInputPort{ctrl: ctrl}
	mock.recorder = &MockAuthInputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthInputPort) EXPECT() *MockAuthInputPortMockRecorder {
	return m.recorder
}

// Auth mocks base method.
func (m *MockAuthInputPort) Auth() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Auth")
}

// Auth indicates an expected call of Auth.
func (mr *MockAuthInputPortMockRecorder) Auth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auth", reflect.TypeOf((*MockAuthInputPort)(nil).Auth))
}

// Callback mocks base method.
func (m *MockAuthInputPort) Callback(token, secret string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Callback", token, secret)
}

// Callback indicates an expected call of Callback.
func (mr *MockAuthInputPortMockRecorder) Callback(token, secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Callback", reflect.TypeOf((*MockAuthInputPort)(nil).Callback), token, secret)
}

// IsAuthenticated mocks base method.
func (m *MockAuthInputPort) IsAuthenticated() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IsAuthenticated")
}

// IsAuthenticated indicates an expected call of IsAuthenticated.
func (mr *MockAuthInputPortMockRecorder) IsAuthenticated() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthenticated", reflect.TypeOf((*MockAuthInputPort)(nil).IsAuthenticated))
}

// Logout mocks base method.
func (m *MockAuthInputPort) Logout() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Logout")
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthInputPortMockRecorder) Logout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthInputPort)(nil).Logout))
}

// MockAuthOutputPort is a mock of AuthOutputPort interface.
type MockAuthOutputPort struct {
	ctrl     *gomock.Controller
	recorder *MockAuthOutputPortMockRecorder
}

// MockAuthOutputPortMockRecorder is the mock recorder for MockAuthOutputPort.
type MockAuthOutputPortMockRecorder struct {
	mock *MockAuthOutputPort
}

// NewMockAuthOutputPort creates a new mock instance.
func NewMockAuthOutputPort(ctrl *gomock.Controller) *MockAuthOutputPort {
	mock := &MockAuthOutputPort{ctrl: ctrl}
	mock.recorder = &MockAuthOutputPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthOutputPort) EXPECT() *MockAuthOutputPortMockRecorder {
	return m.recorder
}

// RenderAuth mocks base method.
func (m *MockAuthOutputPort) RenderAuth(arg0 *entity.Auth) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderAuth", arg0)
}

// RenderAuth indicates an expected call of RenderAuth.
func (mr *MockAuthOutputPortMockRecorder) RenderAuth(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderAuth", reflect.TypeOf((*MockAuthOutputPort)(nil).RenderAuth), arg0)
}

// RenderCallback mocks base method.
func (m *MockAuthOutputPort) RenderCallback(arg0 *entity.Auth) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderCallback", arg0)
}

// RenderCallback indicates an expected call of RenderCallback.
func (mr *MockAuthOutputPortMockRecorder) RenderCallback(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderCallback", reflect.TypeOf((*MockAuthOutputPort)(nil).RenderCallback), arg0)
}

// RenderError mocks base method.
func (m *MockAuthOutputPort) RenderError(arg0 error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderError", arg0)
}

// RenderError indicates an expected call of RenderError.
func (mr *MockAuthOutputPortMockRecorder) RenderError(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderError", reflect.TypeOf((*MockAuthOutputPort)(nil).RenderError), arg0)
}

// RenderIsAuth mocks base method.
func (m *MockAuthOutputPort) RenderIsAuth(arg0 *entity.Auth) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderIsAuth", arg0)
}

// RenderIsAuth indicates an expected call of RenderIsAuth.
func (mr *MockAuthOutputPortMockRecorder) RenderIsAuth(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderIsAuth", reflect.TypeOf((*MockAuthOutputPort)(nil).RenderIsAuth), arg0)
}

// RenderLogout mocks base method.
func (m *MockAuthOutputPort) RenderLogout(arg0 *entity.Auth) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderLogout", arg0)
}

// RenderLogout indicates an expected call of RenderLogout.
func (mr *MockAuthOutputPortMockRecorder) RenderLogout(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderLogout", reflect.TypeOf((*MockAuthOutputPort)(nil).RenderLogout), arg0)
}

// MockAuthRepository is a mock of AuthRepository interface.
type MockAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepositoryMockRecorder
}

// MockAuthRepositoryMockRecorder is the mock recorder for MockAuthRepository.
type MockAuthRepositoryMockRecorder struct {
	mock *MockAuthRepository
}

// NewMockAuthRepository creates a new mock instance.
func NewMockAuthRepository(ctrl *gomock.Controller) *MockAuthRepository {
	mock := &MockAuthRepository{ctrl: ctrl}
	mock.recorder = &MockAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepository) EXPECT() *MockAuthRepositoryMockRecorder {
	return m.recorder
}

// AuthByCallbackParams mocks base method.
func (m *MockAuthRepository) AuthByCallbackParams(token, secret string) (handler.TwitterCredentials, handler.TwitterValues, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthByCallbackParams", token, secret)
	ret0, _ := ret[0].(handler.TwitterCredentials)
	ret1, _ := ret[1].(handler.TwitterValues)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AuthByCallbackParams indicates an expected call of AuthByCallbackParams.
func (mr *MockAuthRepositoryMockRecorder) AuthByCallbackParams(token, secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthByCallbackParams", reflect.TypeOf((*MockAuthRepository)(nil).AuthByCallbackParams), token, secret)
}

// FindUserByTwitterID mocks base method.
func (m *MockAuthRepository) FindUserByTwitterID(twitterID string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByTwitterID", twitterID)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByTwitterID indicates an expected call of FindUserByTwitterID.
func (mr *MockAuthRepositoryMockRecorder) FindUserByTwitterID(twitterID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByTwitterID", reflect.TypeOf((*MockAuthRepository)(nil).FindUserByTwitterID), twitterID)
}

// GetAuthUrl mocks base method.
func (m *MockAuthRepository) GetAuthUrl() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthUrl")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthUrl indicates an expected call of GetAuthUrl.
func (mr *MockAuthRepositoryMockRecorder) GetAuthUrl() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthUrl", reflect.TypeOf((*MockAuthRepository)(nil).GetAuthUrl))
}

// IsAuthenticated mocks base method.
func (m *MockAuthRepository) IsAuthenticated() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuthenticated")
	ret0, _ := ret[0].(error)
	return ret0
}

// IsAuthenticated indicates an expected call of IsAuthenticated.
func (mr *MockAuthRepositoryMockRecorder) IsAuthenticated() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthenticated", reflect.TypeOf((*MockAuthRepository)(nil).IsAuthenticated))
}

// Logout mocks base method.
func (m *MockAuthRepository) Logout() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout")
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockAuthRepositoryMockRecorder) Logout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockAuthRepository)(nil).Logout))
}

// UpdateSession mocks base method.
func (m *MockAuthRepository) UpdateSession(token, secret string, userID int, twitterID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSession", token, secret, userID, twitterID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSession indicates an expected call of UpdateSession.
func (mr *MockAuthRepositoryMockRecorder) UpdateSession(token, secret, userID, twitterID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSession", reflect.TypeOf((*MockAuthRepository)(nil).UpdateSession), token, secret, userID, twitterID)
}

// UpdateTwitterApi mocks base method.
func (m *MockAuthRepository) UpdateTwitterApi(token, secret string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateTwitterApi", token, secret)
}

// UpdateTwitterApi indicates an expected call of UpdateTwitterApi.
func (mr *MockAuthRepositoryMockRecorder) UpdateTwitterApi(token, secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTwitterApi", reflect.TypeOf((*MockAuthRepository)(nil).UpdateTwitterApi), token, secret)
}

// UpsertUser mocks base method.
func (m *MockAuthRepository) UpsertUser(user *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUser", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertUser indicates an expected call of UpsertUser.
func (mr *MockAuthRepositoryMockRecorder) UpsertUser(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUser", reflect.TypeOf((*MockAuthRepository)(nil).UpsertUser), user)
}
